version: '3'
networks:
  mynet:
    external: true
services:
  webapicorefx:
    build: .
    image: webapicorefx
    container_name: webapicorefx
    networks:
      - mynet
    volumes:
      - "/home/lut/webapicorefx:/app"
    restart: always
    ports: 
      - "10080:80"