version: '3'
networks:
 mynet:
   external: true
services:
  usercenterapi.dev:
    build: .
    image: usercenterapi.dev
    container_name: usercenterapi.dev
   networks:
     - mynet
   volumes:
     - "/home/lut/usercenterapi:/app"
    restart: always
    ports: 
      - "10080:80"
