//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Models
{
	/// <summary>
	/// Database       : db_electricity_network
	/// Data Source    : 192.168.0.82
	/// Server Version : 8.0.11
	/// </summary>
	public partial class DbElectricityNetworkDB : LinqToDB.Data.DataConnection
	{
		public ITable<TLog>       TLogs       { get { return this.GetTable<TLog>(); } }
		/// <summary>
		/// 权限表: 权限名称 + 接口名称
		/// </summary>
		public ITable<TPower>     TPowers     { get { return this.GetTable<TPower>(); } }
		/// <summary>
		/// 用户角色信息表
		/// </summary>
		public ITable<TRoleinfo>  TRoleinfoes { get { return this.GetTable<TRoleinfo>(); } }
		/// <summary>
		/// 关联角色和权限的表
		/// </summary>
		public ITable<TRolePower> TRolePowers { get { return this.GetTable<TRolePower>(); } }
		public ITable<TUserinfo>  TUserinfoes { get { return this.GetTable<TUserinfo>(); } }
		public ITable<TUserRole>  TUserRoles  { get { return this.GetTable<TUserRole>(); } }
		/// <summary>
		/// VIEW
		/// </summary>
		public ITable<VRolePower> VRolePowers { get { return this.GetTable<VRolePower>(); } }
		/// <summary>
		/// VIEW
		/// </summary>
		public ITable<VUserRole>  VUserRoles  { get { return this.GetTable<VUserRole>(); } }

		public DbElectricityNetworkDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbElectricityNetworkDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("t_log")]
	public partial class TLog
	{
		[Column("id"),              PrimaryKey,  Identity] public int      Id             { get; set; } // int(11)
		/// <summary>
		/// 模块
		/// </summary>
		[Column("module"),             Nullable          ] public string   Module         { get; set; } // varchar(255)
		/// <summary>
		/// 日志内容
		/// </summary>
		[Column("log"),                Nullable          ] public string   Log            { get; set; } // varchar(500)
		/// <summary>
		/// 操作员身份证号
		/// </summary>
		[Column("operator_idcard"),    Nullable          ] public string   OperatorIdcard { get; set; } // varchar(36)
		/// <summary>
		/// 操作员角色
		/// </summary>
		[Column("operator_role"),      Nullable          ] public string   OperatorRole   { get; set; } // varchar(50)
		/// <summary>
		/// 操作员姓名
		/// </summary>
		[Column("operator_name"),      Nullable          ] public string   OperatorName   { get; set; } // varchar(50)
		[Column("create_time"),     NotNull              ] public DateTime CreateTime     { get; set; } // datetime
	}

	/// <summary>
	/// 权限表: 权限名称 + 接口名称
	/// </summary>
	[Table("t_power")]
	public partial class TPower
	{
		[Column("id"),              PrimaryKey,  Identity] public int       Id             { get; set; } // int(11)
		/// <summary>
		/// 权限名
		/// </summary>
		[Column("power_name"),      NotNull              ] public string    PowerName      { get; set; } // varchar(50)
		/// <summary>
		/// 权限接口
		/// </summary>
		[Column("power_interface"), NotNull              ] public string    PowerInterface { get; set; } // varchar(255)
		[Column("create_time"),        Nullable          ] public DateTime? CreateTime     { get; set; } // datetime
		[Column("update_time"),        Nullable          ] public DateTime? UpdateTime     { get; set; } // datetime
	}

	/// <summary>
	/// 用户角色信息表
	/// </summary>
	[Table("t_roleinfo")]
	public partial class TRoleinfo
	{
		[Column("id"),           PrimaryKey,  Identity] public int       Id         { get; set; } // int(11)
		/// <summary>
		/// 英文角色名
		/// </summary>
		[Column("role_name_en"), NotNull              ] public string    RoleNameEn { get; set; } // varchar(30)
		/// <summary>
		/// 中文角色名
		/// </summary>
		[Column("role_name_cn"), NotNull              ] public string    RoleNameCn { get; set; } // varchar(30)
		[Column("create_time"),     Nullable          ] public DateTime? CreateTime { get; set; } // datetime
		[Column("update_time"),     Nullable          ] public DateTime? UpdateTime { get; set; } // datetime
	}

	/// <summary>
	/// 关联角色和权限的表
	/// </summary>
	[Table("t_role_power")]
	public partial class TRolePower
	{
		[Column("id"),          PrimaryKey,  Identity] public int       Id         { get; set; } // int(11)
		/// <summary>
		/// 角色id
		/// </summary>
		[Column("role_id"),     NotNull              ] public int       RoleId     { get; set; } // int(11)
		/// <summary>
		/// 权限id
		/// </summary>
		[Column("power_id"),    NotNull              ] public int       PowerId    { get; set; } // int(11)
		[Column("create_time"),    Nullable          ] public DateTime? CreateTime { get; set; } // datetime
		[Column("update_time"),    Nullable          ] public DateTime? UpdateTime { get; set; } // datetime
	}

	[Table("t_userinfo")]
	public partial class TUserinfo
	{
		/// <summary>
		/// 自增主键ID
		/// </summary>
		[Column("id"),          PrimaryKey,  Identity] public int       Id         { get; set; } // int(32)
		/// <summary>
		/// 最长18个字符
		/// </summary>
		[Column("idcard"),      NotNull              ] public string    Idcard     { get; set; } // char(18)
		[Column("phone"),       NotNull              ] public string    Phone      { get; set; } // varchar(13)
		[Column("username"),       Nullable          ] public string    Username   { get; set; } // varchar(20)
		[Column("password"),    NotNull              ] public string    Password   { get; set; } // varchar(50)
		/// <summary>
		/// 枚举:男\女
		/// </summary>
		[Column("sex"),            Nullable          ] public char?     Sex        { get; set; } // enum('男','女')
		[Column("email"),          Nullable          ] public string    Email      { get; set; } // varchar(30)
		[Column("create_time"),    Nullable          ] public DateTime? CreateTime { get; set; } // datetime
		[Column("update_time"),    Nullable          ] public DateTime? UpdateTime { get; set; } // datetime
	}

	[Table("t_user_role")]
	public partial class TUserRole
	{
		[Column("id"),          PrimaryKey,  Identity] public int       Id         { get; set; } // int(11)
		/// <summary>
		/// 用户身份证号
		/// </summary>
		[Column("user_idcard"), NotNull              ] public string    UserIdcard { get; set; } // char(36)
		/// <summary>
		/// 角色id
		/// </summary>
		[Column("role_id"),     NotNull              ] public int       RoleId     { get; set; } // int(11)
		[Column("create_time"),    Nullable          ] public DateTime? CreateTime { get; set; } // datetime
		[Column("update_time"),    Nullable          ] public DateTime? UpdateTime { get; set; } // datetime
	}

	/// <summary>
	/// VIEW
	/// </summary>
	[Table("v_role_power", IsView=true)]
	public partial class VRolePower
	{
		[Column("id"),              NotNull    ] public int    Id             { get; set; } // int(11)
		/// <summary>
		/// 角色id
		/// </summary>
		[Column("role_id"),         NotNull    ] public int    RoleId         { get; set; } // int(11)
		/// <summary>
		/// 英文角色名
		/// </summary>
		[Column("role_name_en"),       Nullable] public string RoleNameEn     { get; set; } // varchar(30)
		/// <summary>
		/// 中文角色名
		/// </summary>
		[Column("role_name_cn"),       Nullable] public string RoleNameCn     { get; set; } // varchar(30)
		/// <summary>
		/// 权限id
		/// </summary>
		[Column("power_id"),        NotNull    ] public int    PowerId        { get; set; } // int(11)
		/// <summary>
		/// 权限接口
		/// </summary>
		[Column("power_interface"),    Nullable] public string PowerInterface { get; set; } // varchar(255)
		/// <summary>
		/// 权限名
		/// </summary>
		[Column("power_name"),         Nullable] public string PowerName      { get; set; } // varchar(50)
	}

	/// <summary>
	/// VIEW
	/// </summary>
	[Table("v_user_role", IsView=true)]
	public partial class VUserRole
	{
		/// <summary>
		/// 自增主键ID
		/// </summary>
		[Column("id"),              Nullable] public int?   Id         { get; set; } // int(32)
		/// <summary>
		/// 最长18个字符
		/// </summary>
		[Column("idcard"),          Nullable] public string Idcard     { get; set; } // char(18)
		[Column("phone"),           Nullable] public string Phone      { get; set; } // varchar(13)
		[Column("username"),        Nullable] public string Username   { get; set; } // varchar(20)
		[Column("password"),        Nullable] public string Password   { get; set; } // varchar(50)
		/// <summary>
		/// 枚举:男\女
		/// </summary>
		[Column("sex"),             Nullable] public char?  Sex        { get; set; } // enum('男','女')
		[Column("email"),           Nullable] public string Email      { get; set; } // varchar(30)
		/// <summary>
		/// 角色id
		/// </summary>
		[Column("role_id"),      NotNull    ] public int    RoleId     { get; set; } // int(11)
		/// <summary>
		/// 英文角色名
		/// </summary>
		[Column("role_name_en"),    Nullable] public string RoleNameEn { get; set; } // varchar(30)
		/// <summary>
		/// 中文角色名
		/// </summary>
		[Column("role_name_cn"),    Nullable] public string RoleNameCn { get; set; } // varchar(30)
	}

	public static partial class TableExtensions
	{
		public static TLog Find(this ITable<TLog> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TPower Find(this ITable<TPower> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TRoleinfo Find(this ITable<TRoleinfo> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TRolePower Find(this ITable<TRolePower> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TUserinfo Find(this ITable<TUserinfo> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TUserRole Find(this ITable<TUserRole> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
